checkWithFailure
	self assert: false description: 'A failure'