testInBlockTempShadowing	interactive := true.	self initializeErrorMessage.	text := 'temp |var2| [:temp| |var2|]'.	self flag: 'display menu instead of going into failblock'	"self compileWithFailBlock: [				self assert: (errorMessage = 'Name is already defined ->').				self assert: (errorLocation = 22).				self assert: (errorSource contents = 'temp |var2| [:temp| |var2|]').				^nil]."