new
	self error: 'Use #table:'